---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: lead-radar-erpnext-api
  namespace: lead-radar
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  encryptedData:
    api_key: AgBsitm8QCxjsE4PihLI+pfJ/RdDXFOYF3K9wwHd6dwm2YlxP/0dyZJD3H5epTQuT3EdXnPIPs/s29IPLcS6uRsMFX/cRwjINZfZTgA7YPd1+5FjoNXH+ZXz4V5Jqn74ZD3szuSHUjKcpma475hHPCN82PsSgIolrBlmodibaD4CvrEsWOzSPDzyQISmoKCD61nUlYZg2oI3J2cfQvVuHabXct3rmRq9Lmt321+Wi+/+ACjcOqAY0Fb1wcyx/RwMo3xjnIaAhWkAgRIWPkVLo6WEdpTjYw/WSRUmiD8+jDqwYNUr200sLTbwax/m6aFa4HpaBp/aU26Yg/m64wlvifIxZqkG5xacS9tblIMs2fk6DannBishBymVA4WhvaC2K6Fn0sqQ+D7g7McrwSgXApM9kbFlx+8hvWPd0+PTclsD+gW4gifX3Y5xSJg/NK4XJkTxhLqgW1E/PWvsdtfXoVU7qxE2fDDZsdC76Aa9SeSs1OR7PlrYmukne6/QENULbvm8XXJ048eSRihgzn6fAh6ZF7vgTpjpOg8/EbsG/li6aD6UZqYWXNrPYHV0fkfA3igE+y5bDz3cCz8NeGEOtSaj7E/0m1WxT9dxbbPpeCuqtCrVFAzqMXohTn3ByQepRq87xjltN8XbDYR9SWAPf5fKe6bs4d0t753fZVC6je6ygjW+Rv4vRntHn5GJHQrwMM4XKlYK/kWhZz3Xc1iZj4Q=
    api_secret: AgCRSt6XSUHHhATpvHF/iWN81WUx86jfChyZO6KK1AVEK9DXelOZzQlHCFnlwHkjeYpGeMeEJ2WqKFiLIm9jSegskfFhcvPgNWah2eknoXGv7oERLFrW9nMSijFvBDpaYTpKLHYjzhPBCT6Jq4BDyBFed5b6ifHNKwSoMAzvjTyAGUo95852sE/Iovybz4nuWx0gWaFJFuUR80XuRhpfwbWwQzCchG86XVDLNaihv9kOkUTlbx30IdbNjiYAxpY+iEtt2YKX1K7GfTx78GV05QyGBaHgDC02FFT++IqB9kb9cLc1wvaxxgr1G17UVZyI7SGG+SjAdrS1GHZeTgaoH1MjdGT9AnznJQnHmRuqaeuyZgsy8EZUxy1pYrqajQ8jX06aSU9BZ7FVz/sYZhA9lvx3ERKeQuk1lzUuL+QY9Wo6PCHP7LcTSSDa2EUYMEXVnb88k3TPEgP5nQVpDKDTnOXCjDE/iCtgky7Igky1TeeinjX/ir7xwWxZ5V8nWOTCR+1+GpRj3Igi59c90HJLXNIfKIW/5cwsa0P3FMw3MfQHlQDcLABLIC5YhvEQ1rWJJ+lrcG1CZfvFwa6KRytvJCwELhm3assMOAr7vRnjjeqxtTwUu6S0affpUy3C8+5I6GWlAisxcK7y6BFCs6QFoXDuU14Cn9tXdizMn5hsCGFYc0fGs4/PojXYlyf7e7lHJmftvTMbEBHEl9+1dccErso=
  template:
    metadata:
      creationTimestamp: null
      name: lead-radar-erpnext-api
      namespace: lead-radar
