---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: lead-radar-github
  namespace: lead-radar
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  encryptedData:
    token: AgCgGzS9x5b/UcPab0yzcgB7eNKsBBLIO1cAoMXPxwU9nTXv+LKF3GZiAICVxMLJEiuLj2B8MtEAbb9Q5OytZGiSjKNCkNklFlw64bC2Eh9/SGm8lFXIz7Q78FCxeNKE5kXY3VqPP4Fg6vhi+nfhLyGgZGhwNzLw56grZiSBH8QyUbgIuFJKnnZgjfNSWwKq+muw2x+qd5RPqiFYvo4VZyGpdjWwaT655yrrhsfq/qbbGWX2nM/pWXuSFZlOj2aDBITCwBTkfSCzoe78M3J9shUIsquvE1jHehpSx1WgicISqvRmcT8BASOkejECBODqjhqKa6EyYLDngmQbM/IFw4LzdjJqbE1rSGfrmGi4PjqUUWSxGE28bpeOoN2BZKzLatn/YU696MDlQ0gVn4D7OXFidlWosyJWWln37KOSO9XUoewBlhBTtY43Q6HPdrprCKRGBOwCFUHaKiX3YBGsTGSkCfG8GRPCwMCzo35+hMqKxaaDgRIY3Qr8othxOsPHqDZPaKEoI2xamlN6PyWccp3Fz6t/LDMbjD7EZRnqfYlghHLSgSF8DSlWcvMKXjNh8f5tNu/5EiSkzDb/TIIPKrcewOckJGeuXZQBeu5Gwo6gknCOEJfElY64wS3U4UA7ZGJI6gYhjzrXsSEzkQsqLb27cXaVQYxOosfniHMRiaEz2Sh1a1GQoVQDjL4k8lnnKjZlTKQ1hcqQvD2mglq64hjogXuoI57y4f+UbUvPxGWRCVW3eyvdS6m8
  template:
    metadata:
      creationTimestamp: null
      name: lead-radar-github
      namespace: lead-radar
