---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: lead-radar-cnpg-app
  namespace: lead-radar
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  encryptedData:
    password: AgCWPYF9yXXxlZ/LK41NBQQmbNKvAR7lIeiqBSSjpERzSErzvr23Zseak06rhqCUj0f9Uph0XET8yZUi6VCackFZmQeXVHK0q3IUqrUm32THGkhayU6gHNS54z+wuPF+eN2f9UPCf74mjNSCH9MddozCoQvmdFYgi8DU6Go6C3kZUT3nYIeA2dE7uQewU10DxnmV+67fSlglhY0Xhr9ZJvGOrM49oj1xF1YruHYe9RyiNKQ0RM9DB3iBo6k12x6yTV8LEJcnRIirAD43zYMAzwvWqQrUNCt00deMjjloxNGMxx/y0+Tc2uXYVxm2EhBedvnwVJmJyKHZqS0YbTkZNpVQIsaAHdc1CmrVyxl7jXzpvKd3l+bN+OQCbtds5vBbn6W2FhQk8KyHsVHPlnmGG1PLjrmkEdW7d/LV7fWQuCtnSK3TIA/m7fN7qEPS3SAkD9YYz7ZaxlBjPxY3ztcWOM0m2RLHZkP1z2mJD4e8Of5CrtfO3W55kOtVcLY4nD/5RLBNo5bPv9sIs6C8k1d3TN8o61hXQnJ0yem6QeWNaTxP/mjrfIxrNkVgA/i2vb3hVcPX7ki/99ip22HDHv/wMDdU52HjaDmCwVuBbRcRIqcb2zwXTBWU2b7cvU5wTeJWoxN4epQw73/gWNrVJnMs5aB+0+dWuir+4co+aXmEJ38rNvspcP//E35SKUH6hk7JFTuOXaQ0kELkHT3LutQXl6mYGoE2K2rwgPvslsVQ6sJPilhdsgeIkRdmz4uvgd0YE3Y=
    username: AgC7xoC7kMWua/3/jfj1FUfsT0dbeVxgtJ1xYaDCAAAar1ehHZnN+D6n5XWp1dPq+t3B1Jltjj9LUD3SfjhjPLZmjv9U0hdgHvHk+M86agRjhaSJdK2aUr8WVx0N3bgGBbfTm0vrTNznqrD6l8OzH30M+QWWRcCKtnuqBPQkORb4l83Vrs2Q4slfQ/Qv4vGb4X8GgVISl2j+fyLtIYwhwJbA7mp5epkyxl2aR9nYg/d1lp/X1F8tmKikGVVMwrFe/YfeFJewH0GSx3+0qN6TfQ09p1fE02zihVlhTsHpYQVtCyG55XAttllAkkJqaNJRIVyjbFrW+SL9y7HP7qBDY7f2cBFzTS3BZPpM4F6FJAQlGDkuK0dfNUIvS9oyLY09fFcQCAzUPXT5GE8+UI6sFguPD9TcqvO0f1Ti4LEIHUH1dcsuQdZlcuTu6Y2tMTvAwCNeovVzPOdBFUjrIXskLSGukkFLS2IFEZ3PTgo8yjQUygYaqU2EYem7n/8VNJ0eW0yV7oYyURNWC9hYf0iGwARI1s4g18qs0TGtrrOOePdqgJl4HHAXgYpUEJmS28rVqRzhqPbM2j38NTza8NSVz4XoOZL9tTq79M9PMbq696sPFgniU7nNb6z1Yo8BBj5icpolQbX2DDXOiQ+X/Cd7lz3XchjIDc2V8uZBqtrTJgtog67zB0shACMcBFfEgzjsAruUqQ8ygLIMFtx4
  template:
    metadata:
      creationTimestamp: null
      name: lead-radar-cnpg-app
      namespace: lead-radar
